import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Image from 'next/image';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="/favicon-48x48.png" sizes="48x48" />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <meta name="apple-mobile-web-app-title" content="MyWebSite" />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      

        {/* Canva embed */}
        <div style={{ 
          position: 'relative', 
          width: '100%', 
          height: 0, 
          paddingTop: '56.2225%', 
          paddingBottom: 0, 
          boxShadow: '0 2px 8px 0 rgba(63,69,81,0.16)', 
          marginTop: '1.6em', 
          marginBottom: '0.9em', 
          overflow: 'hidden',
          borderRadius: 8, 
          willChange: 'transform' 
        }}>
          <iframe 
            loading="lazy" 
            style={{ 
              position: 'absolute', 
              width: '100%', 
              height: '100%', 
              top: 0, 
              left: 0, 
              border: 'none', 
              padding: 0, 
              margin: 0 
            }}
            src="https://www.canva.com/design/DAGTjdkBcto/TJe4cTAQIsS1IdMi6nrJOg/view?embed" 
            allowFullScreen={true} 
            allow="fullscreen"
          />
        </div>
        <a href="https://www.canva.com/design/DAGTjdkBcto/TJe4cTAQIsS1IdMi6nrJOg/view?utm_content=DAGTjdkBcto&utm_campaign=designshare&utm_medium=embeds&utm_source=link" target="_blank" rel="noopener">
          Ready to walkaway a winner!
        </a> by n0rv311

        {/* Games Page Content */}
        <div className="container mx-auto p-8">
          <h2 className="text-3xl font-bold mb-4 text-old-gold-500">Explore More Games</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
            <GameCard 
              imageSrc="/game1.png" 
              link="https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?gameSymbol=vs15fghtmultlv&websiteUrl=https%3A%2F%2Fdemogamesfree.pragmaticplay.net&jurisdiction=99&lobby_url=https%3A%2F%2Fwww.pragmaticplay.com%2Fen%2F&lang=EN&cur=USD"  
            />
            <GameCard 
              imageSrc="/game2.png" 
              link="https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?gameSymbol=vs20olympgate&websiteUrl=https%3A%2F%2Fdemogamesfree.pragmaticplay.net&jurisdiction=99&lobby_url=https%3A%2F%2Fwww.pragmaticplay.com%2Fen%2F&lang=EN&cur=USD" 
            />
            <GameCard 
              imageSrc="/game3.png" 
              link="https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?gameSymbol=vswayskrakenmw&websiteUrl=https%3A%2F%2Fdemogamesfree.pragmaticplay.net&jurisdiction=99&lobby_url=https%3A%2F%2Fwww.pragmaticplay.com%2Fen%2F&lang=EN&cur=USD" 
            />
            <GameCard 
              imageSrc="/game4.png" 
              link="https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?gameSymbol=vs10bbdoubled&websiteUrl=https%3A%2F%2Fdemogamesfree.pragmaticplay.net&jurisdiction=99&lobby_url=https%3A%2F%2Fwww.pragmaticplay.com%2Fen%2F&lang=EN&cur=USD" 
            />
          </div>
        </div>

        {children} 
      </body>
    </html>
  );
}

// GameCard component
function GameCard({ imageSrc, link }: { imageSrc: string; link: string }) {
  return (
    <a href={link} target="_blank" rel="noopener noreferrer">
      <Image 
        src={imageSrc}
        alt="Game Image"
        width={200} 
        height={50} 
      />
    </a>
  );
}